"""tests/test_cli.py — Comprehensive unit tests for SwarmCron CLI."""

import json
from pathlib import Path
from swarmcron.cli import main, export_system_crontab_lines
from swarmcron.core import SwarmCronRegistry, SwarmCronTask


def test_cli_register_and_list(tmp_path: Path, capsys) -> None:
    store_file = tmp_path / "custom_tasks.json"
    
    # 1. Register task via CLI
    ret = main([
        "--store", str(store_file),
        "register",
        "--id", "backup-db",
        "--name", "Daily Database Backup",
        "--schedule", "0 2 * * *",
        "--command", "python3 -c \"print('backup done')\"",
        "--tags", "backup,critical",
        "--group", "infrastructure",
        "--timeout", "120",
    ])
    assert ret == 0
    captured = capsys.readouterr()
    registered_data = json.loads(captured.out)
    assert registered_data["ok"] is True
    assert registered_data["task"]["id"] == "backup-db"
    assert registered_data["task"]["tags"] == ["backup", "critical"]
    assert registered_data["task"]["timeout_seconds"] == 120

    # 2. List tasks via CLI
    ret_list = main(["--store", str(store_file), "list"])
    assert ret_list == 0
    captured_list = capsys.readouterr()
    tasks_list = json.loads(captured_list.out)
    assert len(tasks_list) == 1
    assert tasks_list[0]["id"] == "backup-db"


def test_cli_run_and_recover(tmp_path: Path, capsys) -> None:
    store_file = tmp_path / "tasks.json"
    
    # Register task
    main([
        "--store", str(store_file),
        "register",
        "--id", "health-ping",
        "--name", "Service Health Ping",
        "--schedule", "*/5 * * * *",
        "--command", "python3 -c \"print('ping ok')\"",
    ])
    capsys.readouterr() # clear stdout

    # Run task
    ret_run = main(["--store", str(store_file), "run", "health-ping"])
    assert ret_run == 0
    captured_run = capsys.readouterr()
    run_res = json.loads(captured_run.out)
    assert run_res["success"] is True
    assert run_res["receipt"]["status"] == "success"
    assert "ping ok" in run_res["receipt"]["stdout"]

    # Recover task with custom max-retries
    ret_rec = main(["--store", str(store_file), "recover", "health-ping", "--max-retries", "2"])
    assert ret_rec == 0
    captured_rec = capsys.readouterr()
    rec_res = json.loads(captured_rec.out)
    assert rec_res["success"] is True
    assert rec_res["replays_count"] == 2


def test_cli_mutate_actions(tmp_path: Path, capsys) -> None:
    store_file = tmp_path / "tasks.json"
    
    main([
        "--store", str(store_file),
        "register",
        "--id", "task-mut",
        "--name", "Mutable Task",
        "--schedule", "manual",
        "--command", "true",
    ])
    capsys.readouterr()

    # Pause
    ret_pause = main(["--store", str(store_file), "mutate", "task-mut", "pause"])
    assert ret_pause == 0
    pause_res = json.loads(capsys.readouterr().out)
    assert pause_res["task"]["state"] == "paused"

    # Resume
    ret_resume = main(["--store", str(store_file), "mutate", "task-mut", "resume"])
    assert ret_resume == 0
    resume_res = json.loads(capsys.readouterr().out)
    assert resume_res["task"]["state"] == "active"


def test_cli_export_crontab(tmp_path: Path, capsys) -> None:
    store_file = tmp_path / "tasks.json"
    
    main([
        "--store", str(store_file),
        "register",
        "--id", "cron-export-1",
        "--name", "Cron 1",
        "--schedule", "*/15 * * * *",
        "--command", "python3 worker.py",
        "--cwd", "/tmp",
    ])
    capsys.readouterr()

    ret = main(["--store", str(store_file), "export-crontab", "--include-header"])
    assert ret == 0
    out = capsys.readouterr().out
    assert "# Generated by SwarmCron" in out
    assert "*/15 * * * * cd /tmp && python3 worker.py" in out
