"""SwarmCron CLI command interface."""

import argparse
import json
import shlex
import sys
from pathlib import Path
from typing import Sequence

from .core import SwarmCronRegistry, SwarmCronTask


def export_system_crontab_lines(registry: SwarmCronRegistry) -> list[str]:
    """Generate crontab-compatible lines for all active scheduled tasks."""
    lines: list[str] = []
    for task in registry.load():
        if task.state != "active" or task.schedule == "manual":
            continue
        command = " ".join(shlex.quote(part) for part in task.command)
        lines.append(f"{task.schedule} cd {shlex.quote(str(task.cwd))} && {command}")
    return lines


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="swarmcron",
        description="SwarmCron — DAG Cron Scheduler & Receipt Engine",
    )
    parser.add_argument(
        "--store",
        type=str,
        default=None,
        help="Path to the tasks.json store file (default: ~/.swarmcron/tasks.json or $SWARMCRON_STORE)",
    )

    sub = parser.add_subparsers(dest="cmd", required=True)

    # list
    sub.add_parser("list", help="List all registered tasks as JSON")

    # export-crontab
    export = sub.add_parser("export-crontab", help="Export active tasks as crontab lines")
    export.add_argument("--include-header", action="store_true", help="Include a header comment")

    # run
    run = sub.add_parser("run", help="Execute a task immediately")
    run.add_argument("task_id", help="Task ID to run")

    # recover
    recover = sub.add_parser("recover", help="Replay missed executions")
    recover.add_argument("task_id", help="Task ID to recover")
    recover.add_argument(
        "--max-retries",
        type=int,
        default=3,
        help="Maximum number of replay attempts (default: 3)",
    )

    # mutate
    mutate = sub.add_parser("mutate", help="Perform a lifecycle action on a task")
    mutate.add_argument("task_id", help="Task ID to mutate")
    mutate.add_argument("action", choices=["pause", "resume", "deactivate", "activate", "delete"])

    # register
    register = sub.add_parser("register", help="Register a new task")
    register.add_argument("--id", required=True, dest="task_id", help="Unique task identifier")
    register.add_argument("--name", required=True, help="Human-readable task name")
    register.add_argument(
        "--schedule",
        required=True,
        help='Cron expression (5-field) or "manual"',
    )
    register.add_argument(
        "--command",
        required=True,
        help="Shell command to execute (will be parsed into tokens)",
    )
    register.add_argument("--group", default="general", help="Task group (default: general)")
    register.add_argument("--cwd", default=".", help="Working directory (default: .)")
    register.add_argument("--depends-on", default="", help="Comma-separated upstream task IDs")
    register.add_argument("--tags", default="", help="Comma-separated tags")
    register.add_argument(
        "--timeout",
        type=int,
        default=600,
        help="Timeout in seconds (default: 600)",
    )

    args = parser.parse_args(argv)

    # Build registry with custom store path if provided
    store_path = Path(args.store) if args.store else None
    registry = SwarmCronRegistry(path=store_path)

    if args.cmd == "list":
        print(json.dumps([t.to_dict() for t in registry.load()], indent=2, sort_keys=True))
        return 0

    if args.cmd == "export-crontab":
        lines = export_system_crontab_lines(registry)
        if args.include_header:
            print("# Generated by SwarmCron (https://github.com/mbgulden/swarmcron)")
        print("\n".join(lines))
        return 0

    if args.cmd == "run":
        res = registry.mutate(args.task_id, "run")
        print(json.dumps(res, indent=2, sort_keys=True))
        return 0 if res.get("success") else 1

    if args.cmd == "recover":
        res = registry.mutate(args.task_id, "recover", max_retries=args.max_retries)
        print(json.dumps(res, indent=2, sort_keys=True))
        return 0 if res.get("success") else 1

    if args.cmd == "mutate":
        res = registry.mutate(args.task_id, args.action)
        print(json.dumps(res, indent=2, sort_keys=True))
        return 0

    if args.cmd == "register":
        depends_on = [d.strip() for d in args.depends_on.split(",") if d.strip()]
        tags = [t.strip() for t in args.tags.split(",") if t.strip()]
        task = SwarmCronTask(
            id=args.task_id,
            name=args.name,
            schedule=args.schedule,
            command=shlex.split(args.command),
            group=args.group,
            cwd=args.cwd,
            depends_on=depends_on,
            tags=tags,
            timeout_seconds=args.timeout,
        )
        registry.register(task)
        print(json.dumps({"ok": True, "task": task.to_dict()}, indent=2, sort_keys=True))
        return 0

    return 2


if __name__ == "__main__":
    sys.exit(main())
