"""SwarmCron CLI command interface."""

import argparse
import json
import shlex
import sys
from pathlib import Path
from typing import Sequence

from .core import SwarmCronRegistry, SwarmCronTask


def export_system_crontab_lines(registry: SwarmCronRegistry) -> list[str]:
    lines: list[str] = []
    for task in registry.load():
        if task.state != "active" or task.schedule == "manual":
            continue
        command = " ".join(shlex.quote(part) for part in task.command)
        lines.append(f"{task.schedule} cd {shlex.quote(str(task.cwd))} && {command}")
    return lines


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="SwarmCron — DAG Cron Scheduler & Receipt Engine")
    sub = parser.add_subparsers(dest="cmd", required=True)

    sub.add_parser("list")

    export = sub.add_parser("export-crontab")
    export.add_argument("--include-header", action="store_true")

    run = sub.add_parser("run")
    run.add_argument("task_id")

    recover = sub.add_parser("recover")
    recover.add_argument("task_id")

    mutate = sub.add_parser("mutate")
    mutate.add_argument("task_id")
    mutate.add_argument("action", choices=["pause", "resume", "deactivate", "activate", "delete"])

    args = parser.parse_args(argv)
    registry = SwarmCronRegistry()

    if args.cmd == "list":
        print(json.dumps([t.to_dict() for t in registry.load()], indent=2, sort_keys=True))
        return 0
    if args.cmd == "export-crontab":
        lines = export_system_crontab_lines(registry)
        if args.include_header:
            print("# Generated by SwarmCron (https://github.com/mbgulden/swarmcron)")
        print("\n".join(lines))
        return 0
    if args.cmd == "run":
        res = registry.mutate(args.task_id, "run")
        print(json.dumps(res, indent=2, sort_keys=True))
        return 0 if res.get("success") else 1
    if args.cmd == "recover":
        res = registry.mutate(args.task_id, "recover")
        print(json.dumps(res, indent=2, sort_keys=True))
        return 0 if res.get("success") else 1
    if args.cmd == "mutate":
        res = registry.mutate(args.task_id, args.action)
        print(json.dumps(res, indent=2, sort_keys=True))
        return 0
    return 2


if __name__ == "__main__":
    sys.exit(main())
